### ISSUE TITLE
Can't build ionic app with --prod

### ISSUE THREAD

**Issue by maxakash** [sajTempler/IonicFirebasePhoneAuth#1]
while building ionic app in production mode, app stucks at copying or showsj avascript  running out of memory space.

**Comment by simon-ntitle** [comment]
Hey, can u please provide `ionic info` ;)

**Comment by sajTempler** [comment]
Hey,
Please provide `ionic info`

**Comment by maxakash** [comment]
here it is
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 13
other plugins)

System:

   NodeJS : v10.1.0 (/usr/local/bin/node)
   npm    : 5.0.2
   OS     : macOS

**Comment by maxakash** [comment]
here it is 
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 13 other plugins)

System:

   NodeJS : v10.1.0 (/usr/local/bin/node)
   npm    : 5.0.2
   OS     : macOS

**Comment by sajTempler** [comment]
Hey,
issue should be solved - more details can be found here: [https://github.com/firebase/firebase-js-sdk/issues/848](url)

**Comment by maxakash** [comment]
Hey, thanks buddy , you definitely saved my day. It's working perfectly now. Anyways where was the problem?

**Comment by sajTempler** [comment]
The problem was that firebase sdk changed the way on importing their packages - supposedly ;)

**Comment by maxakash** [comment]
Hey,

I just signed the petition "Human Resource Department of India: Remove 75%
Attendance Bar in Graduate Colleges" and wanted to see if you could help by
adding your name.

Our goal is to reach 68,237 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2DKmf9E

Thanks!
Akash
