### ISSUE TITLE
iOS can use it or not ?

### ISSUE THREAD

**Issue by uokivan** [sajTempler/IonicFirebasePhoneAuth#3]
Thank you very much

**Comment by sajTempler** [comment]
Yes,

If you have problems while trying it. Create an issue with question

Happy coding
Simon

**Comment by uokivan** [comment]
Thank you very much

**Comment by uokivan** [comment]
Hi sajTempler

on android ,when I use  this "IonicFirebasePhoneAuth", 
I can get the verify code from firebase, but when I insert the verify code, and press "verify" button,
It do nothing.....my I wrong??

**Comment by sajTempler** [comment]
Do u see this line in console after typing code from sms ?

console.log('LoginPage user', user);

**Comment by uokivan** [comment]
Hi sajTempler
Thanks for your help,
now I make it , Thanks so so much

**Comment by uokivan** [comment]
Update : 
Android can get the verify code, all done 👍 
iOS can get the verify code too........but can't click the "verify" button, It do nothing
in xcode, it shows : CDVIonicKeyboard: updating frame

**Comment by sajTempler** [comment]
Hey,

Unfortunately I don't have iOS device. But it worked in one of the projects that I was involved.

here are some more info on it (go to verifyPhoneNumber section)
https://arnesson.github.io/cordova-plugin-firebase/docs/API.html
